name: string-analyzer
region: nyc
services:
  - name: web
    environment_slug: python
    github:
      repo: Kalanza/string-analyzer
      branch: master
      deploy_on_push: true
    build_command: pip install -r requirements.txt
    run_command: uvicorn string-analyzer.app.main:app --host 0.0.0.0 --port ${PORT:-8000}
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: ENVIRONMENT
        value: production
        scope: RUN_TIME
databases:
  - name: string-analyzer-db
    engine: PG
    version: "15"
    production: false
    cluster_name: string-analyzer-db-cluster
